<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_lembar_perhitungan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_lembar_perhitungan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $tb_lembar_perhitungan = $this->Tb_lembar_perhitungan_model->get_all();

        $data = array(
            'tb_lembar_perhitungan_data' => $tb_lembar_perhitungan
        );

        $this->load->view('tb_lembar_perhitungan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Tb_lembar_perhitungan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'uniqid' => $row->uniqid,
		'nomor' => $row->nomor,
		'tanggal' => $row->tanggal,
		'nama_pemohon' => $row->nama_pemohon,
		'lokasi_persil' => $row->lokasi_persil,
	    );
            $this->load->view('tb_lembar_perhitungan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_lembar_perhitungan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tb_lembar_perhitungan/create_action'),
	    'uniqid' => set_value('uniqid'),
	    'nomor' => set_value('nomor'),
	    'tanggal' => set_value('tanggal'),
	    'nama_pemohon' => set_value('nama_pemohon'),
	    'lokasi_persil' => set_value('lokasi_persil'),
	);
        $this->load->view('tb_lembar_perhitungan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nomor' => $this->input->post('nomor',TRUE),
		'tanggal' => $this->input->post('tanggal',TRUE),
		'nama_pemohon' => $this->input->post('nama_pemohon',TRUE),
		'lokasi_persil' => $this->input->post('lokasi_persil',TRUE),
	    );

            $this->Tb_lembar_perhitungan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tb_lembar_perhitungan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tb_lembar_perhitungan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tb_lembar_perhitungan/update_action'),
		'uniqid' => set_value('uniqid', $row->uniqid),
		'nomor' => set_value('nomor', $row->nomor),
		'tanggal' => set_value('tanggal', $row->tanggal),
		'nama_pemohon' => set_value('nama_pemohon', $row->nama_pemohon),
		'lokasi_persil' => set_value('lokasi_persil', $row->lokasi_persil),
	    );
            $this->load->view('tb_lembar_perhitungan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_lembar_perhitungan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('uniqid', TRUE));
        } else {
            $data = array(
		'nomor' => $this->input->post('nomor',TRUE),
		'tanggal' => $this->input->post('tanggal',TRUE),
		'nama_pemohon' => $this->input->post('nama_pemohon',TRUE),
		'lokasi_persil' => $this->input->post('lokasi_persil',TRUE),
	    );

            $this->Tb_lembar_perhitungan_model->update($this->input->post('uniqid', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tb_lembar_perhitungan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tb_lembar_perhitungan_model->get_by_id($id);

        if ($row) {
            $this->Tb_lembar_perhitungan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tb_lembar_perhitungan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_lembar_perhitungan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nomor', 'nomor', 'trim|required');
	$this->form_validation->set_rules('tanggal', 'tanggal', 'trim|required');
	$this->form_validation->set_rules('nama_pemohon', 'nama pemohon', 'trim|required');
	$this->form_validation->set_rules('lokasi_persil', 'lokasi persil', 'trim|required');

	$this->form_validation->set_rules('uniqid', 'uniqid', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tb_lembar_perhitungan.php */
/* Location: ./application/controllers/Tb_lembar_perhitungan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-26 17:27:50 */
/* http://harviacode.com */