<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_surat_permohonan_imb extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_surat_permohonan_imb_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $tb_surat_permohonan_imb = $this->Tb_surat_permohonan_imb_model->get_all();

        $data = array(
            'tb_surat_permohonan_imb_data' => $tb_surat_permohonan_imb
        );

        $this->load->view('tb_surat_permohonan_imb_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Tb_surat_permohonan_imb_model->get_by_id($id);
        if ($row) {
            $data = array(
		'surat_permohonan' => $row->surat_permohonan,
		'alamat_permohonan' => $row->alamat_permohonan,
	    );
            $this->load->view('tb_surat_permohonan_imb_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_surat_permohonan_imb'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tb_surat_permohonan_imb/create_action'),
	    'surat_permohonan' => set_value('surat_permohonan'),
	    'alamat_permohonan' => set_value('alamat_permohonan'),
	);
        $this->load->view('tb_surat_permohonan_imb_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'surat_permohonan' => $this->input->post('surat_permohonan',TRUE),
		'alamat_permohonan' => $this->input->post('alamat_permohonan',TRUE),
	    );

            $this->Tb_surat_permohonan_imb_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tb_surat_permohonan_imb'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tb_surat_permohonan_imb_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tb_surat_permohonan_imb/update_action'),
		'surat_permohonan' => set_value('surat_permohonan', $row->surat_permohonan),
		'alamat_permohonan' => set_value('alamat_permohonan', $row->alamat_permohonan),
	    );
            $this->load->view('tb_surat_permohonan_imb_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_surat_permohonan_imb'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'surat_permohonan' => $this->input->post('surat_permohonan',TRUE),
		'alamat_permohonan' => $this->input->post('alamat_permohonan',TRUE),
	    );

            $this->Tb_surat_permohonan_imb_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tb_surat_permohonan_imb'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tb_surat_permohonan_imb_model->get_by_id($id);

        if ($row) {
            $this->Tb_surat_permohonan_imb_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tb_surat_permohonan_imb'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_surat_permohonan_imb'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('surat_permohonan', 'surat permohonan', 'trim|required');
	$this->form_validation->set_rules('alamat_permohonan', 'alamat permohonan', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tb_surat_permohonan_imb.php */
/* Location: ./application/controllers/Tb_surat_permohonan_imb.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-27 06:18:53 */
/* http://harviacode.com */