<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_divisi_subdivisi_model extends CI_Model
{

    public $table = 'tb_divisi_subdivisi';
    public $id = 'uniqid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('uniqid,id,id_parent,nama_divisi,jenis');
        $this->datatables->from('tb_divisi_subdivisi');
        //add this line for join
        //$this->datatables->join('table2', 'tb_divisi_subdivisi.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tb_divisi_subdivisi/read/$1'),'Read')." | ".anchor(site_url('tb_divisi_subdivisi/update/$1'),'Update')." | ".anchor(site_url('tb_divisi_subdivisi/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'uniqid');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('uniqid', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_parent', $q);
	$this->db->or_like('nama_divisi', $q);
	$this->db->or_like('jenis', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('uniqid', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_parent', $q);
	$this->db->or_like('nama_divisi', $q);
	$this->db->or_like('jenis', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tb_divisi_subdivisi_model.php */
/* Location: ./application/models/Tb_divisi_subdivisi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-02 07:59:51 */
/* http://harviacode.com */